#################################
# 筱锋工具箱配置文件                #
# 作者：筱锋xiao_lfeng            #
# 博客：https://www.x-lf.com/    #
# 版本：1.0.0-Alpha              #
#################################

###
# 基础配置信息
###
# 插件前缀显示
Global_Prefix: "§2XF§b§lTools"

###
# OP管理
###
# 赋予OP密码
OP_Password: 20040227

###
# 插件管理
###
# 是否开启凋落物保护
Plugin_Drop: true
# 是否开启违禁物品检测
Plugin_BanBlock: true
BanBlock_List:
  - "BEDROCK"
  - "COMMAND_BLOCK"
# 是否开启玩家指令记录
Plugin_CommandLog: true
# 是否开启管理员指令记录
Plugin_CommandAdminLog: true

###
# 数据库配置信息
###
Mysql_Open: false
Mysql_Host: "localhost"
Mysql_Port: 3306
Mysql_User: ""
Mysql_Password: ""
Mysql_SSL: false